server:
  port: 8000
  servlet-path: /
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:conf/Mybatis.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://188.131.223.181:3306/panda_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: panda
    dbcp2:
      initial-size: 5
      max-wait-millis: 10000
      max-idle: 20
      min-idle: 5
      soft-min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
  redis:
    host: 123.56.87.111
    port: 6379
    pool:
      max-idle: 8
      max-wait: -1
      max-active: 8
      min-idle: 0
    timeout: 0
    password:

logging:
  level.com.wang.server.dao: debug
